<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{cholBatch}
-->


## Chol
```{r package}
#library(Matrix)

```


```{r cpu_function}
a1 = matrix(c(25,15,-5,15,18,0,-5,0,11),nrow=3,ncol=3,byrow=TRUE)
x <- chol(a1)   ## start from factor given by chol
y <- diag(x)   ## extract sqrt(D)
L1 <- t(x/y)     ## get unit lower triangular factor
D1 <- diag(x^2)  ## and diagonal


a2 = matrix(c(2,5,-5,5,16,3,-5,3,85),nrow=3,ncol=3, byrow=TRUE)
x <- chol(a2)   ## start from factor given by chol
y <- diag(x)   ## extract sqrt(D)
L2 <- t(x/y)     ## get unit lower triangular factor
D2 <- diag(x^2)  ## and diagonal


A1 = cbind(c(0,0,0,0), rbind(c(0,0,0),a1))  #4x4
A2 = cbind(c(0,0,0,0), rbind(c(0,0,0),a2))

rbind(A1,A2)
L1;D1;L2;D2
```

```{r chol_two_batch}
library(gpuRandom)
library(gpuR)
gpuA<-vclMatrix(rbind(A1,A2),type="float")
diagMat = vclMatrix(0, 3, ncol(A1), type = "float")
NglobalChol =  c(4,4,1)
NlocalChol = c(2,4,1)
NlocalCache = 100
gpuRandom:::cholBatchBackend(gpuA, diagMat, c(1,3,1,3), c(1,2,0,3), 2L,
                             NglobalChol, NlocalChol, NlocalCache)

as.matrix(gpuA)
as.matrix(diagMat)



library(gpuRandom)
library(gpuR)
gpuA<-vclMatrix(rbind(A1,A2),type="double")
diagMat = vclMatrix(0, 3, ncol(A1), type = "double")
NglobalChol =  c(4,4,1)
NlocalChol = c(2,4,1)
NlocalCache = 100
gpuRandom:::cholBatchBackend(gpuA, diagMat, c(1,3,1,3), c(1,2,0,3), 2L,
                             NglobalChol, NlocalChol, NlocalCache)

as.matrix(gpuA)
as.matrix(diagMat)
```


```{r chol_R_function}
rbind(a1,a2)
a<-vclMatrix(rbind(a1,a2),type="float")
diagMat = vclMatrix(0, 2, ncol(a1), type = "float")
result<-gpuRandom::cholBatch(a, diagMat, numbatchD=2L,
                             Nglobal=NglobalChol, Nlocal=NlocalChol, NlocalCache=NlocalCache)

L1;D1;L2;D2
as.matrix(a)
as.matrix(diagMat)
```











```{r chol test Aug27, eval=F}
 
library("gpuR")
library("gpuRandom")
library('geostatsp')
library("raster")
Nsim = 2
Ngrid = c(25, 25)
NlocalCache = 1000
Nglobal = c(8L, 8L, 8L)
Nlocal = c(4L, 2L)
theType = "double"


myRaster = raster(
  extent(0,Ngrid[1]/Ngrid[2],5,6),
  Ngrid[2], Ngrid[1]
)
coordsSp = sp::SpatialPoints(xyFromCell(myRaster, 1:ncell(myRaster)))
coordsGpu = vclMatrix(coordsSp@coords, 
                      nrow(coordsSp@coords), 
                      ncol(coordsSp@coords), type=theType)
# x = rbind(
#   c(shape=5.25, range=1.5, variance = 1, nugget = 0, anisoRatio = 1, anisoAngleRadians = 0))


myParamsBatch = rbind(c(shape=5.25, range=0.1, variance = 1, nugget = 0, anisoRatio = 1, anisoAngleRadians = 0),
  c(shape=5.25, range=1, variance = 1, nugget = 0, anisoRatio = 1, anisoAngleRadians = 0))

paramsGpu = gpuRandom::maternGpuParam(myParamsBatch, type=theType)

myParamsBatch = t(apply(myParamsBatch, 1, geostatsp::fillParam))
myParamsBatch = cbind(myParamsBatch, matrix(0, nrow(myParamsBatch), 22-ncol(myParamsBatch)))



maternMatrix = vclMatrix(0, nrow(paramsGpu)*nrow(coordsGpu), 
                         nrow(coordsGpu),type=theType)
dim(maternMatrix)
gpuRandom::maternBatch(maternMatrix, coordsGpu, paramsGpu, c(64,64), c(2,4))


var4cpu = geostatsp::matern(
  x=coordsSp,
  param=drop(myParamsBatch[1,1:7])
)

var4gpu = maternMatrix[1:prod(Ngrid), ]
dim(var4cpu)
range(var4cpu - var4gpu)

diagMat = vclMatrix(0, nrow(paramsGpu), ncol(maternMatrix), type = theType)
gpuRandom::cholBatch(maternMatrix, diagMat, numbatchD=nrow(myParamsBatch),
                     Nglobal = c(8L, 8L, 8L),Nlocal=c(2,2,2),3000)



cholCpu = as.matrix(chol(var4cpu))
theDiag = diag(cholCpu)
cholCpu = cholCpu %*% diag(1/theDiag)
theDiag = theDiag^2

chol4gpu = as.matrix(maternMatrix[1:prod(Ngrid),])
chol4gpu[upper.tri(chol4gpu)] = 0
diag(chol4gpu) = 1

 # chol4gpu[300:400,1:4]
 # cholCpu[300:400,1:4]
range(cholCpu - chol4gpu)
range(theDiag - as.matrix(diagMat)[1,])







(cholCpu - chol4gpu)[200:300,100:200]

dim(cholCpu)


```









