<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Create_Streams_GPU}
-->



```{r test uint3, eval=FALSE}
library(clrng)
library(gpuR)

###CPU streams
streams1 <- createStreamsCpu(n=4, initial=12345)



###GPU streams
myStreamsGpu1 = vclMatrix(streams1, type="double")

myStreamsGpu2 = createStreamsGpu(n=4, initial=c(12345,12345,22,44,33,88))
t(as.matrix(myStreamsGpu2))

myStreamsGpu3 = createStreamsGpu(n=4)
t(as.matrix(myStreamsGpu3))
```




```{r test uint3, eval=FALSE}
library(gpuRandom)
library(gpuR)

###GPU stream
seedR<-gpuR::vclVector(c(12345, 12345, 12345, 12345, 12345, 12345),type="integer")
streamsGPU<-vclMatrix(0L, nrow=4, ncol=18, type="integer")
gpuRandom:::CreateStreamsGpuBackend(creatorInitialGlobalR=seedR, 
                                    streamsR=streamsGPU, 
                                    keepInitial=1)
t(as.matrix(streamsGPU))



seedR <- c(12345L, 12345L, 12345L, 12345L, 12345L, 12345L)
streamsGpu <- gpuRandom::CreateStreamsGpu(seedR, 5L, keepInitial=TRUE)
streams <- as.matrix(streamsGpu)
gpuR::colnames(streams) = c("current.g1.1", "current.g1.2", "current.g1.3", "current.g2.1", "current.g2.2", "current.g2.3",
                             "initial.g1.1", "initial.g1.2", "initial.g1.3", "initial.g2.1", "initial.g2.2", "initial.g2.3",
                             "substream.g1.1", "substream.g1.2", "substream.g1.3", "substream.g2.1", "substream.g2.2", "substream.g2.3")
t(streams) 

t(gpuRandom::CreateStreamsCpu(5))
```





