<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Fisher test}
-->

`https://github.com/clMathLibraries/clRNG`


## Fisher test simulation

```{r date}
date()
```


```{r packages, results='hide'}
library('gpuR')
```

```{r memoryAvailable, echo=TRUE, results='hide'}
#setContext(   grep('OpenCL 2.1', listContexts()$platform)[1]    )
gpuInfo()$deviceName   #gpuInfo()$maxAllocatableMem/(1024^3)
```






Example 1
```{r, eval=TRUE}
x<- matrix(c(2, 5, 15, 3), nrow = 2)
fisher.test(x, alternative = "t",  simulate.p.value = T, B = 1e5)



Nglobal = c(64,128)
streams = gpuRandom::CreateStreamsGpu(Nstreams=prod(Nglobal))
streams2=deepcopy(streams)

x<-vclMatrix(x,type="integer")
res1 = gpuRandom::fisher.sim(x, 1e5, streams, returnStatistics=T, type="double", Nglobal=Nglobal)
res1$p.value


res2 = gpuRandom::fisher.sim(x, 1e5, streams2, returnStatistics=T, type="double", Nglobal=Nglobal)
res2$p.value

```



example 3
```{r eg3, eval=FALSE}
#compare results with R fisher function

Job <- matrix(c(1,2,1,0, 3,3,6,1, 10,10,14,9, 6,7,12,11), 4, 4)
fisher.test(Job, simulate.p.value = TRUE, B = 1e5) # also close to 0.78



library("gpuR")
library("gpuRandom")
Nglobal = c(64,128)
streams <- CreateStreamsGpu(Nstreams =8192, keepInitial=1)
Job<-gpuR::vclMatrix(Job, type="integer")


result3<-gpuRandom::fisher.sim(Job, 1e5, returnStatistics=T, 
                             type="double", streams=streams, Nglobal = Nglobal)

result3$p.value


result3$counts
result3$simNum
```













Example 4
```{r  teaTasting, eval=F}
TeaTasting <-matrix(c(3, 1, 1, 3),nrow=2)

TeaTasting
## Using the R function 
fisher.test(TeaTasting, alternative = "t",  simulate.p.value = TRUE, B = 1e5)


Nglobal = c(16,64)
TeaTasting<-vclMatrix(TeaTasting,type="integer")
result<-gpuRandom::fisher.sim(TeaTasting, 100000L, returnStatistics=F, 
                             type="double", Nglobal=c(16,64))

result$p.value
result
```










