<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{loglikelihood_p}
-->

```{r makeplotsCPU,eval=TRUE}
library('geostatsp')
data('swissRain')
sr2 = swissRain
sr2$sqrtY = sqrt(sr2$rain)
sr2$elev = raster::extract(swissAltitude, sr2)

spatialmodel = likfitLgm(
  data=sr2,
  formula=sqrtY ~ elev,
  param=c(range=50000,shape=0.5),  #paramToEstimate = c("range", "nugget", "shape"),  #will make it different
  reml=FALSE,
  verbose=FALSE
)
# spatialmodel = likfitLgm(
#   data=sr2, 
#   formula=rain ~ elev,
#   param=c(range=50000,shape=1.5),
#   reml=FALSE,
#   verbose=FALSE
# )
spatialmodel$parameters

newParamList = list(
  range=seq(20000, 90000 , len=50),
  nugget = seq(0,0.5,len=30)
) 
newParam= do.call(expand.grid, newParamList)

res= mapply(
  function(range, nugget) {
    loglikLgm(
      c(spatialmodel$parameters[c('shape')], 
        range = unname(range), nugget = unname(nugget)),
      data = sr2,
      formula = spatialmodel$model$formula,
      reml = spatialmodel$model$reml,
      minustwotimes=TRUE)
  },
  range = newParam$range,
  nugget = newParam$nugget
)

lMatrix = matrix(res, length(newParamList[[1]]), length(newParamList[[2]]))

myCol = mapmisc::colourScale(lMatrix, breaks=8, dec=0)
image(
  newParamList[[1]]/1000, newParamList[[2]], lMatrix,
  col = myCol$col, breaks=myCol$breaks,
  xlab = names(newParamList)[1],
  ylab = names(newParamList)[2]	
)
mapmisc::legendBreaks('topright', myCol)
```

```{r makeplots newGPU11.22}
library(gpuRandom)
library(gpuR)
library('geostatsp')
data('swissRain')

swissRain$sqrtY = sqrt(swissRain$rain)
swissRain$elevation = extract(swissAltitude, swissRain)


newParamList = list(
  range=seq(20000, 90000 , len=50),
  nugget = seq(0,0.5,len=30),
  shape = 0.5,
  anisoRatio = 1, 
  anisoAngleRadians = 0
) 
newParam= do.call(expand.grid, newParamList)


library(data.table)
system.time(result3 <- gpuRandom::likfitLgmGpu(data=swissRain,
                        formula=sqrtY~ elevation, 
                        coordinates=swissRain@coords,
                        paramToEstimate = NULL, 
                        #variance and regression parameters are always estimated
                        params=newParam, # CPU matrix for now, users need to provide proper parameters given their specific need
                        BoxCox = c(1, 0),
                        type = "double",
                        reml=FALSE, 
                        minustwotimes=TRUE,
                        NparamPerIter=100,
                        Nglobal=c(128,64),
                        Nlocal=c(16,16),
                        NlocalCache=2600,
                        verbose=FALSE))

result3$table
# result3$LogLik
minusTwoLogLik=as.matrix(result3$minusTwoLogLik)


lMatrix = matrix(minusTwoLogLik[,1], length(newParamList[[1]]), length(newParamList[[2]]))
# 
myCol = mapmisc::colourScale(lMatrix, breaks=8, dec=0)
image(
  newParamList[[1]]/1000, newParamList[[2]], lMatrix,
  col = myCol$col, breaks=myCol$breaks,
  xlab = names(newParamList)[1],
  ylab = names(newParamList)[2]
)
mapmisc::legendBreaks('topright', myCol)
```



```{r makeplotsGPU,eval=TRUE}
# isotropic
library(gpuRandom)
library(gpuR)
library('geostatsp')
data('swissRain')
sr2 = swissRain[0:100,]


######### note whether a variance is present here makes a difference in plots
# newParamList = list(
#   range=seq(20000, 90000 , len=50),
#   nugget = seq(0,0.3,len=30),
#   shape = 1.5,
#   variance=1.894534,
#   anisoRatio = 1, 
#   anisoAngleRadians = 0
# ) 


newParamList = list(
  range=seq(20000, 90000 , len=50),
  nugget = seq(0,0.5,len=30),
  shape = 1.5,
  anisoRatio = 1, 
  anisoAngleRadians = 0
) 
newParam= do.call(expand.grid, newParamList)


# params0 = geostatsp::fillParam(newParam)
# paramsGpu = gpuR::vclMatrix(cbind(params0, matrix(0, nrow(params0), 22-ncol(params0))),type=type)


paramsGpu = gpuRandom::maternGpuParam(newParam, type="double")
system.time(result<-gpuRandom::likfitGpu(spatialmodel,     #data,
                               type = "double",
                               paramsGpu, #a vclmatrix, consists of all the parameters#betas=NULL, #a vclmatrix  #only one row batch, but many colbatches
                               BoxCox=c(1,0.5), # an R vector, will always be c(1,0,.....)
                               form = "ml",
                               NparamPerIter=100,  # how many sets of params to be evaluated in each loop
                               nBetahats =1,
                               minustwotimes=TRUE,
                               Nglobal=c(128,64,1),
                               Nlocal=c(16,16,1),
                               NlocalCache=2600))
#as.matrix(result$XVYXVX)
#result$Betahats
result<-gpuRandom::likfitGpu(spatialmodel,     #data,
                               type = "double",
                               paramsGpu, #a vclmatrix, consists of all the parameters#betas=NULL, #a vclmatrix  #only one row batch, but many colbatches
                               BoxCox=c(1,0.5), # an R vector, will always be c(1,0,.....)
                               form = "ml",
                               NparamPerIter=100,  # how many sets of params to be evaluated in each loop
                               nBetahats =1,
                               minustwotimes=TRUE,
                               Nglobal=c(128,64,1),
                               Nlocal=c(16,32,1),
                               NlocalCache=2600)
mTwoLogLik <- as.matrix(result$minusTwoLogLik)

lMatrix = matrix(mTwoLogLik[,1], length(newParamList[[1]]), length(newParamList[[2]]))
# 
myCol = mapmisc::colourScale(lMatrix, breaks=8, dec=0)
image(
  newParamList[[1]]/1000, newParamList[[2]], lMatrix,
  col = myCol$col, breaks=myCol$breaks,
  xlab = names(newParamList)[1],
  ylab = names(newParamList)[2]
)
mapmisc::legendBreaks('topright', myCol)


```





```{r test1031}
result$Betahats
as.matrix(result$ssqBetahat)
as.vector(result$detVar)
as.vector(result$jacobian)
as.vector(result$detReml)
as.matrix(result$ssqY)
as.matrix(result$XVYXVX)

```

```{r likfit_givenBeta10.31}
Betas <- t(expand.grid(intercept = seq(3,4,len=5), elevation = 5.4e-05))

result2<-gpuRandom::likfit_givenBeta(Betas = Betas,
                                     variances = paramsBatch0[,4],
                                     Nobs = 100,
                                     detVar=result$detVar,
                                     ssqY=result$ssqY,
                                     XVYXVX=result$XVYXVX,
                                     jacobian=result$jacobian,
                                     form = "mlFixSigma",
                                     minustwotimes=TRUE)

result2$likForBeta
result2$index

```






```{r test11.17}
# isotropic
library(gpuRandom)
library(gpuR)
library('geostatsp')
data('swissRain')
sr2 = swissRain[0:100,]

# extract variables for modeling
sr2$sqrtY = sqrt(sr2$rain)
sr2$elev = raster::extract(swissAltitude, sr2)


spatialmodel = geostatsp::likfitLgm(
  data=sr2,
  formula=sqrtY ~ elev,
  param=c(range=50000,shape=1),
  reml=FALSE,
  verbose=FALSE
)
spatialmodel$parameters

newParamList = list(
  range=seq(30000, 80000 , len=20),
  nugget = seq(0,0.25,len=10)
) 


newParam= do.call(expand.grid, newParamList)

otherparams = c(shape=1, variance=2.016713, anisoRatio = 1, anisoAngleRadians = 0)
otherparams = matrix(rep(otherparams,each=nrow(newParam)),nrow=nrow(newParam))
colnames(otherparams) <- c("shape", "variance", "anisoRatio", "anisoAngleRadians")

paramsBatch0 = cbind(newParam, otherparams)
paramsGpu = gpuRandom::maternGpuParam(paramsBatch0, type="double")

type = "double"


result<-gpuRandom::likfitGpu(spatialmodel,     #data,
                               type = "double",
                               paramsGpu, #a vclmatrix, consists of all the parameters#betas=NULL, #a vclmatrix  #only one row batch, but many colbatches
                               BoxCox=c(1,0), # an R vector, will always be c(1,0,.....)
                               form = "NULL",
                               NparamPerIter=200,  # how many sets of params to be evaluated in each loop
                               nBetahats =1,
                               minustwotimes=TRUE,
                               Nglobal=c(64,64,1),
                               Nlocal=c(16,16,1),
                               NlocalCache=2000)

result
```













```{r test10.5, eval=FALSE}
library(gpuRandom)
library(gpuR)
library('geostatsp')
data('swissRain')
sr2 = swissRain[0:100,]

# extract variables for modeling
sr2$sqrtY = sqrt(sr2$rain)
sr2$elev = raster::extract(swissAltitude, sr2)

newParamList = list(
  range=seq(30000, 80000 , len=20),
  nugget = seq(0,0.25,len=10)
) 


newParam= do.call(expand.grid, newParamList)

otherparams = c(shape=1, variance=1.840997, anisoRatio = 1, anisoAngleRadians = 0)
otherparams = matrix(rep(otherparams,each=nrow(newParam)),nrow=nrow(newParam))
colnames(otherparams) <- c("shape", "variance", "anisoRatio", "anisoAngleRadians")

paramsBatch0 = cbind(newParam, otherparams)
paramsBatch0 = t(apply(paramsBatch0, 1, geostatsp::fillParam))
#paramsGpu = gpuRandom::maternGpuParam(paramsBatch0, type="double")
paramsBatch0=cbind(paramsBatch0, matrix(0, nrow(paramsBatch0),22-ncol(paramsBatch0)))
paramsGpu = gpuR::vclMatrix(paramsBatch0,type="double")



x = sr2
boxcox = c(1,0)
Scov = c('elev')
yvar = 'sqrtY'

# this setting works
workgroupSize = c(64,64,1)
localSize = c(4,8,1)
NlocalCache=1000
verbose = 9L


if(boxcox[1] != 1) {
  boxcox = c(1, 0, setdiff(boxcox, c(0,1)))
}
Ncov = length(Scov)+1
Ndata = length(boxcox)    # =3
Nparam = nrow(paramsGpu)  # =8
# 20*20


type="double"
yx = vclMatrix(cbind(
  as.vector(x@data[,yvar]),
  matrix(0, nrow(x@data), length(boxcox)-1),
  1,
  as.matrix(x@data[,Scov])
), type=type)


coords = vclMatrix(x@coords, type =type)

boxcoxGpu = vclVector(boxcox, type=type)
#betas <- matrix(c(4.441053, 5.809251e-05),nrow=Ncov, ncol=Ndata)
betas <- matrix(0,nrow=Ncov, ncol=Ndata)
betas = vclMatrix(betas, type=type)


detVar = vclVector(0, Nparam,type=type)
detReml = vclVector(0, Nparam, type=type)
jacobian = vclVector(0, Ndata, type=type)
ssqY <- vclMatrix(0, Nparam, Ndata, type=type)
ssqBetahat <- vclMatrix(0, Nparam, Ndata, type=type)
ssqBeta <- vclMatrix(0, Nparam, Ndata, type=type)

NparamPerIter = 50

# objects for debugging
ssqYX = vclMatrix(0, ncol(yx) * NparamPerIter, ncol(yx), type=type)
aTDinvb_beta = vclMatrix(0, Nparam, Ndata, type=type)
XVYXVX = vclMatrix(-77, Nparam * Ncov, ncol(yx), type=type)
ssqYXcopy = vclMatrix(0, ncol(yx) * NparamPerIter, ncol(yx), type=type)
LinvYX = vclMatrix(0, nrow(yx) * NparamPerIter, ncol(yx), type=type)
QinvSsqYx = vclMatrix(0, NparamPerIter*Ncov, Ndata, type = type)
varMat = vclMatrix(0, nrow(yx)*NparamPerIter, nrow(yx), type=type)
cholXVXdiag = vclMatrix(0, NparamPerIter, Ncov, type=type)
cholDiagMat = vclMatrix(0, NparamPerIter, nrow(yx), type=type)
b_beta = vclMatrix(0, NparamPerIter*nrow(yx), Ndata, type=type)

gpuRandom:::likfitGpu_BackendP(
  yx,  #1
  coords,
  paramsGpu,
  boxcoxGpu,  #betas,  #5
  ssqY,#aTDinvb_beta,
  XVYXVX,
  ssqBetahat, #ssqBeta,
  detVar,
  detReml,
  jacobian,  #13
  NparamPerIter,  
  workgroupSize,  
  localSize,  
  NlocalCache,  
  verbose=c(1,0),  #18
  ssqYX, #
  ssqYXcopy,  #new
  LinvYX,  #21
  QinvSsqYx, 
  cholXVXdiag, #23
  varMat, #new
  cholDiagMat)
  #b_beta)   #new  26



any(is.na(as.vector(detVar)))
any(is.na(as.matrix(varMat)))
dim(XVYXVX)
dim(ssqBeta)
# as.vector(detVar)[51:100]
# as.vector(detReml)[51:100]
# as.matrix(ssqBetahat)[40:70,]
# is.na(as.matrix(ssqBetahat))
# as.matrix(ssqBeta)[1:10,]
# as.matrix(aTDinvb_beta)[33:65,]
# as.matrix(b_beta)[1:10,]
# as.matrix(LinvYX)[30:60,]
# as.matrix(ssqYX)
# as.matrix(ssqY)[80:110,]
# any(is.na(as.matrix(ssqYX)))
# as.matrix(XVYXVX)
# as.vector(jacobian)
# as.matrix(cholDiagMat)
# as.matrix(varMat)[10:30,]
# as.matrix(cholDiagMat)

```















