<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Random uniform}
-->


`https://github.com/clMathLibraries/clRNG`



```{r date}
date()
```


```{r packages, results='hide'}
library('gpuR')
```

Use double precision if the GPU supports it
```{r setType}
theType = c('float','double')[1+gpuInfo()$double_support]
theType
#setContext(   grep('gpu', listContexts()$device_type) [2]    )
```














#new random normals
```{r rnorm}

streams <- createStreamsGpu(n =512*128, keepInitial=1)

a<-gpuRandom::rnorm(c(1024,512), streams=streams, 
                                Nglobal=c(512,128), type="float")

avector<-as.vector(as.matrix(a))
hist(avector,breaks=40)
gpuRandom::qqnorm(avector, workgroupSize = Nglobal)

```



#new random uniforms
```{r unif}
b<-gpuRandom::runif(c(200,800), Nglobal=c(64,4), type="double")
bvector<-as.vector(as.matrix(b))
hist(bvector, breaks=40)
```




#new random exponentials
```{r exp}
library("gpuR")
library("gpuRandom")
b<-gpuRandom::rexp(c(2000,600), rate=1, Nglobal=c(64,4), type="double")
bvector<-as.vector(as.matrix(b))
hist(bvector,probability = TRUE)

c<-gpuRandom::rexp(c(2000,600), rate=2, Nglobal=c(64,4), type="double")
cvector<-as.vector(as.matrix(c))
hist(bvector,probability = TRUE)

plot(density(bvector))

hist(cvector,probability  = TRUE)
```















