<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{loglikelihood_p}
-->
```{r geostatsp}
library('geostatsp')
data("swissRain")
swissRain$elevation = extract(swissAltitude, swissRain)

swissRes =  lgm( formula=rain~ elevation, 
                 data=swissRain, 
                 grid=20,
                 covariates=swissAltitude, 
                 reml = FALSE,
                 fixBoxcox=FALSE, fixShape=FALSE, fixNugget = FALSE,  #Set to FALSE to estimate the nugget effect parameter.
                 aniso=TRUE )


swissRes$summary[,c('estimate','ci0.005', 'ci0.995')]
swissRes$summary[,c('estimate','ci0.025', 'ci0.975')]
swissRes$optim$mle
```






```{r test1,eval=TRUE}
library(gpuRandom)
library(gpuR)
library(data.table)
library('geostatsp')
data('swissRain')
swissRain$elevation = extract(swissAltitude, swissRain)

# params = expand.grid(
#   range = exp(seq(log(15), log(260), len=11))*1000, #c(15, 20, 25, 30, 35, 40,  60,  80, 100, 120, 130, 140, 150, 170, 180, 190, 200, 220, 250)*1000,#exp(seq(log(10), log(250), len=12)), #
#   shape = c(0.1, 0.3, 0.5, 1, 1.5, 2, 2.5, 3, 4),
#   anisoRatio = seq(1, 15,len=10),
#   anisoAngleDegrees = seq(27,46, len=10),
#   nugget = c(0, exp(seq(log(0.05), log(6), len=12)))#seq(0, 10,len=5)     # at least c(0,5) to avoid that strange profile
# )
# theMle = swissRes$parameters[c('range','shape', 'anisoRatio', 'anisoAngleDegrees', 'nugget')]
# theMle['nugget'] = swissRes$optim$mle['nugget']
# params = rbind(params, theMle)


params = expand.grid(
  range = c(exp(seq(log(15), log(swissRes$parameters['range']/1000), len=6))*1000, exp(seq(log(swissRes$parameters['range']/1000+5), log(250), len=6))*1000),
  shape = c(seq(0.1, swissRes$parameters['shape'], len=5), seq(swissRes$parameters['shape']+0.5, 6, len=5)),
  anisoRatio =c( seq(1, swissRes$parameters['anisoRatio'], len=5), seq(swissRes$parameters['anisoRatio']+1, 12, len=5) ),
  anisoAngleDegrees = c( seq(27,swissRes$parameters['anisoAngleDegrees'], len=5),  seq(swissRes$parameters['anisoAngleDegrees']+2, 46, len=5)),
  nugget = c(seq(0, swissRes$optim$mle['nugget'], len=3), seq(swissRes$optim$mle['nugget']+0.5, 8, len=8))
)
params = expand.grid(
  range = c(exp(seq(log(15), log(swissRes$parameters['range']/1000), len=6))*1000, exp(seq(log(swissRes$parameters['range']/1000+5), log(250), len=6))*1000),
  shape = c(seq(0.1, swissRes$parameters['shape'], len=5), seq(swissRes$parameters['shape']+0.5, 6, len=5)),
  nugget = c(seq(0, swissRes$optim$mle['nugget'], len=3), seq(swissRes$optim$mle['nugget']+0.5, 8, len=8))
)



cilevel=0.95
data=swissRain
formula=rain~ elevation
coordinates=swissRain@coords
paramToEstimate = c("range","shape","nugget","anisoAngleDegrees", "anisoRatio", "boxcox")
params=params # CPU matrix for now, users need to provide proper parameters given their specific need
boxcox =  c(seq(0.1, 0.8, len=8), swissRes$parameters['boxcox'])
type = "double"
reml=FALSE
minustwotimes=FALSE
NparamPerIter=400
Nglobal=c(128,64)
Nlocal=c(16,16)
NlocalCache=2800
verbose=FALSE

# adding shape = 0.2 ? or boxcox = (-1,2) will make beta's and stderror's profile strange,
# try boxcox = (-1,2) or (-1, 3) will see stderror strange profile
#########################################################
system.time(result1<-gpuRandom::likfitLgmGpu(
                         data=swissRain,
                         formula=rain~ elevation, 
                         coordinates=swissRain@coords,
                         params=params, # CPU matrix for now, users need to provide proper parameters given their specific need
                         boxcox = c(seq(0.1, 0.8, len=8), swissRes$parameters['boxcox']),# (seq(-1,3,len=8),
                         paramToEstimate = c("range","shape","nugget","anisoAngleDegrees", "anisoRatio", "boxcox"), #variance and regression parameters are always estimated
                         cilevel=0.95,
                         type = "double",
                         reml=FALSE, 
                         minustwotimes=FALSE,
                         NparamPerIter=400,
                         Nglobal=c(128,64),
                         Nlocal=c(16,16),
                         NlocalCache=2800,
                         verbose=FALSE))

result1$Ncov
result1$Ndata
result1$estimates
# temp=as.matrix(result1$XVYXVX)
# dim(temp)
# temp[1:12,1:12]

#1.479909e-04
```




```{r betascalar}
Betas <- seq(-6, 18, len=25)*1e-04
system.time(result2<-gpuRandom::betascalarProfile(Betas, #a m x 1 R vector  given by the user 
                                        cilevel=0.95,                         
                                        a=2,     # which beta?   beta1 is intercept, beta2 is first covariate
                                        Nobs=result1$Nobs,  # number of observations.
                                        Ndata=result1$Ndata,
                                        Nparam=result1$Nparam,
                                        Ncov=result1$Ncov,
                                        result1$detVar, # vclVector
                                        result1$ssqY,   # vclMatrix
                                        result1$XVYXVX,   # vclMatrix
                                        result1$jacobian # vclVector  #form = c("loglik", "profileforBeta"),
                                        ))


result2$estimates
result2$breaks
#0.0001791278
#0.0001513466
#0.0001757909
#0.0001825992
plot(Betas,result2$LogLik)
abline(h=result2$breaks)
# max(result2)
f1 <- splinefun(Betas, result2$LogLik, method = "natural")
curve(f1(x), add = TRUE, col = 2, n = 1001)
# a<-optimize(f1, c(min(Betas), max(Betas)), maximum = TRUE, tol = 0.0001)
# breaks <- a$objective - qchisq(0.95,  df = 1)/2
# 
# plot(Betas,result2-breaks)
# f2 <- splinefun(Betas, -0.5*result2-breaks, method = "fmm")
# curve(f2(x), add = TRUE, col = 2, n = 1001)
# abline(h=0)
#  ci<-rootSolve::uniroot.all(f2, lower = min(Betas, upper = max(Betas))
#     if(length(ci)==1){
#       ci <- c(lower, ci)
#     }

############################## intercept ########################################
Betas <- seq(0, 12, len=20)
system.time(result22<-gpuRandom::betascalarProfile(Betas, #a m x 1 R vector  given by the user 
                         cilevel=0.95,                         
                         a=1,     # which beta?   beta1 is intercept, beta2 is first covariate
                         Nobs=result1$Nobs,  # number of observations.
                         Ndata=result1$Ndata,
                         Nparam=result1$Nparam,
                         Ncov=result1$Ncov,
                         result1$detVar, # vclVector
                         result1$ssqY,   # vclMatrix
                         result1$XVYXVX,   # vclMatrix
                         result1$jacobian # vclVector  #form = c("loglik", "profileforBeta"),
                         ))

result22$estimates
#4.404231
plot(Betas,result22$LogLik)
abline(h=result22$breaks)
f2 <- splinefun(Betas, result22$LogLik, method = "natural")
curve(f2(x), add = TRUE, col = 2, n = 1001)
```



```{r variance}
  stderror <- seq(0, 18, len=25)
  system.time(result3<-gpuRandom::variancePro(stderror, #a vector  given by the user 
                                              cilevel=0.95,
                                              Nobs=result1$Nobs,  # number of observations.
                                              Nparam=result1$Nparam,
                                              Ndata=result1$Ndata,
                                              detVar=result1$detVar, # vclVector
                                              ssqResidual=result1$ssqResidual,   # vclMatrix
                                              jacobian=result1$jacobian # vclVector  #form = c("loglik", "profileforBeta"),
                                              ))


  plot(stderror,result3$LogLik)
  result3$estimates
  result3$breaks


 stderror <-c( seq(0,2, len=7), seq(3,18,len=9))
 system.time(result3<-gpuRandom::variancePro(stderror, #a vector  given by the user 
                                              cilevel=0.95,
                                              Nobs=result1$Nobs,  # number of observations.
                                              Nparam=result1$Nparam,
                                              Ndata=result1$Ndata,
                                              detVar=result1$detVar, # vclVector
                                              ssqResidual=result1$ssqResidual,   # vclMatrix
                                              jacobian=result1$jacobian # vclVector  #form = c("loglik", "profileforBeta"),
                                              ))


  plot(stderror,result3$LogLik)
  result3$estimates
  abline(h=result3$breaks)

```





























